/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ["'Space Grotesk'", "sans-serif"],
        sans: ["'Inter'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      colors: {
        brand: {
          50: "#e6faf3",
          100: "#b3f0da",
          200: "#80e5c1",
          300: "#4ddba8",
          400: "#26d494",
          500: "#00c880",
          600: "#00a86a",
          700: "#008854",
          800: "#00683e",
          900: "#004828",
        },
        cyber: {
          50: "#eef3ff",
          100: "#c8dafe",
          200: "#a2befd",
          300: "#7ca2fc",
          400: "#5686fb",
          500: "#306afa",
          600: "#2857d0",
          700: "#2044a6",
          800: "#18317c",
          900: "#101e52",
        },
        ember: {
          50: "#fff4ed",
          100: "#ffe0cc",
          200: "#ffccaa",
          300: "#ffb888",
          400: "#ffa466",
          500: "#ff9044",
          600: "#d57a3a",
          700: "#ab6430",
          800: "#814e26",
          900: "#57381c",
        },
        surface: {
          light: "#ffffff",
          "light-secondary": "#f8f9fb",
          "light-tertiary": "#f0f2f5",
          "light-border": "#e2e5ea",
          dark: "#0a0c10",
          "dark-secondary": "#12151b",
          "dark-tertiary": "#1a1e28",
          "dark-border": "#262b38",
          "dark-hover": "#1f2430",
        },
        text: {
          light: "#1a1d23",
          "light-secondary": "#6b7280",
          "light-tertiary": "#9ca3af",
          dark: "#edeff3",
          "dark-secondary": "#8d96a8",
          "dark-tertiary": "#565e70",
        },
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "fade-up": "fadeUp 0.5s ease-out",
        "slide-in-right": "slideInRight 0.3s ease-out",
        "slide-in-left": "slideInLeft 0.3s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
        "float": "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 3s ease-in-out infinite",
        "sweep": "sweep 3.4s linear infinite",
        "glow": "glow 2s ease-in-out infinite alternate",
        "shimmer": "shimmer 2s linear infinite",
        "orbit": "orbit 8s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(10px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-10px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        sweep: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        glow: {
          "0%": { boxShadow: "0 0 20px rgba(0, 200, 128, 0.1)" },
          "100%": { boxShadow: "0 0 40px rgba(0, 200, 128, 0.3)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        orbit: {
          "0%": { transform: "rotate(0deg) translateX(120px) rotate(0deg)" },
          "100%": { transform: "rotate(360deg) translateX(120px) rotate(-360deg)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
