"""Add user role for RBAC

Revision ID: 845e027ff51d
Revises: 7ad3179add76
Create Date: 2026-07-03 17:33:44.576687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845e027ff51d'
down_revision: Union[str, Sequence[str], None] = '7ad3179add76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "manager",
                "analyst",
                "viewer",
                name="user_role",
            ),
            nullable=False,
            server_default="viewer",
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
